config/urls.py
# from django.contrib import admin
from django.urls import path, include
from django.contrib import admin
import core.urls

# from core import admin
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(core.urls, namespace='core')),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    path('movies', views.MovieList.as_view(), name='MovieList'),
    path('movie/<int:pk>', views.MovieDetail.as_view(), name='MovieDetail'),
]

core/models.py
from django.db import models


class Movie(models.Model):
    RATED_G = 0
    RATED_PG = 1
    RATED_PG_13 = 2
    RATED_R = 3
    NOT_RATED = 4
    RATINGS = (
        (RATED_G, 'G - General Audience'),
        (RATED_PG, 'PG - Parental Guidance'),
        (RATED_PG_13, 'PG-13 - Parents Strongly Cautioned'),
        (RATED_R, 'R - Restricted'),
        (NOT_RATED, 'NR - Not Rated'),
    )

    title = models.CharField(
        max_length=140)
    plot = models.TextField()
    year = models.PositiveIntegerField()
    rating = models.IntegerField(
        choices=RATINGS,
        default=NOT_RATED
    )
    runtime = \
        models.PositiveIntegerField()
    website = models.URLField(blank=True)

    class Meta:
        ordering = ('-year', 'title')

    def __str__(self):
        return '{} ({})'.format(self.title, self.year)

core/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from core.models import Movie


class MovieDetail(DetailView):
    model = Movie


class MovieList(ListView):
    model = Movie
    paginate_by = 10

core/templates/core/movie_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ object.title }} - {{ block.super }}
{% endblock %}

{% block main %}
    <h1>{{ object }}</h1>
    <p class="lead">
        {{ object.plot }}
    </p>
{% endblock %}

{% block sidebar %}
    <div>
        This movie is rated:
        <span class="badge badge-primary">
            {{ object.get_rating_display }}
        </span>
    </div>
{% endblock %}

core/templates/core/movie_list.html
{% extends 'base.html' %}

{% block title %}
    All The Movies
{% endblock %}

{% block main %}
    <ul>
        {% for movie in object_list %}
            <li>
                <a href="{% url 'core:MovieDetail' pk=movie.id %}">{{ movie }}</a>
            </li>
        {% endfor %}
    </ul>
    {% if is_paginated %}
        <nav>
            <ul class="pagination">
                <li class="page-item">
                    <a href="{% url 'core:MovieList' %}?page=1"
                       class="page-link"
                    >First</a>
                </li>
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a href="{% url 'core:MovieList' %}?page={{ page_obj.previous_page_number }}"
                           class="page-link"
                        >
                            {{ page_obj.previous_page_number }}
                        </a>
                    </li>
                {% endif %}
                <li class="page-item active">
                    <a href="{% url 'core:MovieList' %}?page={{ page_obj.number }}"
                       class="page-link">
                        {{ page_obj.number }}
                    </a>
                </li>
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a href="{% url 'core:MovieList' %}?page={{ page_obj.next_page_number }}"
                           class="page-link">
                            {{ page_obj.next_page_number }}
                        </a>
                    </li>
                {% endif %}
                <li class="page-item">
                    <a href="{% url 'core:MovieList' %}?page=last"
                       class="page-link">Last</a>
                </li>
            </ul>
        </nav>
    {% endif %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
    >
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
    <title>{% block title %}MyMDB{% endblock %}
    </title>
    <style>
        .mymdb-masthead {
            background-color: #EEE;
            margin-bottom: 1em;
        }
    </style>
</head>
<body>
<div class="mymdb-masthead">
    <div class="container">
        <nav class="nav">
            <div class="navbar-brand">MyMDB</div>
            <a href="{% url 'core:MovieList' %}" class="nav-link">Movies</a>
        </nav>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-sm-8 mymdb-main">
            {% block main %}{% endblock %}
        </div>
        <div class="col-sm-3 offset-sm-1 mymdb-sidebar">
            {% block sidebar %}{% endblock %}
        </div>
    </div>
</div>
</body>
</html>